
server.port: 8080
server.error.include-message: always

spring.cloud.function.definition: messageProcessor
spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.messageProcessor-in-0:
    destination: products
    group: productsGroup

spring.cloud.stream.bindings.messageProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    se.magnus.microservices: DEBUG
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: product-db
server:
  port: 8080
spring.rabbitmq.host: rabbitmq
spring.cloud.stream.kafka.binder.brokers: kafka